import { Inter } from "next/font/google";
import "./globals.css";
import NavigationCard from "../components/bottomNavigation/NavigationCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aishwary Patle",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <NavigationCard />
      </body>
    </html>
  );
}
